# Generated by Django 4.1.4 on 2022-12-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elektro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('mark', models.CharField(max_length=50, verbose_name='Марка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('description', models.TextField(verbose_name='+')),
                ('img', models.ImageField(upload_to='photo')),
            ],
            options={
                'verbose_name': 'Електро',
                'verbose_name_plural': 'Електроники',
            },
        ),
    ]
