# Generated by Django 4.1.4 on 2022-12-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acsessuar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('mark', models.CharField(max_length=50, verbose_name='Марка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('description', models.TextField(verbose_name='+')),
                ('img', models.ImageField(upload_to='photo')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
            },
        ),
        migrations.CreateModel(
            name='Nout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('mark', models.CharField(max_length=50, verbose_name='Марка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('description', models.TextField(verbose_name='+')),
                ('img', models.ImageField(upload_to='photo')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуктар',
            },
        ),
    ]
